org.gradle.jvmargs=-Xmx2G

enabledPlatforms=neoforge,fabric

version=3.0.0-alpha.1
group=com.github.moshangca.extractinator

resourcefulLibMCVersion=1.21
minecraftVersion=1.21.1
parchmentVersion=2024.11.17

resourcefulLibVersion=3.0.12
resourcefulConfigVersion=3.0.11

reiVersion=16.0.799
jeiVersion=19.44.0.403
