modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/moshang-ca/Extractinator/issues"

[[mods]]
modId = "extractinator"
version = "${version}"
displayName = "Extractinator Forked"
# displayURL = "https://modrinth.com/mod/extractinator"
logoFile = "icon.png"
authors = "Alex Nijjar, Moshang"
credits = "Alex Nijjar, Kekie6"
description = "Convert blocks into resources."

[[mixins]]
config = "extractinator.mixins.json"

[[dependencies.extractinator]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21, 1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefullib"
mandatory = true
versionRange = "[3.0.12,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[3.0.11,)"
ordering = "NONE"
side = "BOTH"